from __future__ import annotations

from dataclasses import dataclass
import math


def clamp(value: float, low: float, high: float) -> float:
    return max(low, min(high, value))


@dataclass
class VehicleParams:
    """Minimal lateral dynamics parameters for a constant-speed dynamic bicycle model.

    Notes
    -----
    - Units are SI.
    - Cf/Cr are axle cornering stiffnesses per tire pair modelled as 2*Cf and 2*Cr in the equations.
    - steering_ratio converts steering-wheel angle [rad] to road-wheel angle [rad].
    """

    m: float = 1600.0
    iz: float = 2500.0
    lf: float = 1.25
    lr: float = 1.55
    cf: float = 80000.0
    cr: float = 90000.0
    vx: float = 20.0
    dt: float = 0.05

    tau_rwa: float = 0.12
    tau_sfa: float = 0.18
    steering_ratio: float = 15.0

    max_rwa: float = 0.35          # road-wheel angle [rad]
    max_sfa: float = 6.0           # steering-wheel angle [rad]
    max_rwa_rate: float = 2.5      # [rad/s]
    max_sfa_rate: float = 12.0     # [rad/s]


@dataclass
class VehicleState:
    x: float = 0.0
    y: float = 0.0
    psi: float = 0.0
    vy: float = 0.0
    r: float = 0.0
    delta_rwa: float = 0.0
    delta_sfa: float = 0.0
    lam: float = 1.0
    t: float = 0.0


def equivalent_rwa_from_sfa(delta_sfa: float, params: VehicleParams) -> float:
    """Convert steering-wheel angle to equivalent road-wheel angle."""
    delta_rwa_eq = delta_sfa / max(params.steering_ratio, 1e-6)
    return clamp(delta_rwa_eq, -params.max_rwa, params.max_rwa)



def blend_rwa_command(lam: float, delta_drv_rwa: float, delta_auto_rwa: float) -> float:
    """Convex blend between driver and automation road-wheel commands.

    lam = 1  -> full driver authority
    lam = 0  -> full automation authority
    """
    lam = clamp(lam, 0.0, 1.0)
    delta_cmd = lam * delta_drv_rwa + (1.0 - lam) * delta_auto_rwa
    return delta_cmd



def step_vehicle(
    state: VehicleState,
    rwa_cmd: float,
    sfa_cmd: float,
    params: VehicleParams,
) -> VehicleState:
    """One forward-Euler step of the minimal SBW lateral model.

    Inputs
    ------
    rwa_cmd : final road-wheel command used by the chassis controller / authority allocator.
    sfa_cmd : steering-wheel side command generated by the driver model.

    Returns
    -------
    VehicleState : next state.
    """
    dt = params.dt
    vx = max(params.vx, 0.1)

    # 1) Actuator dynamics -------------------------------------------------
    # Road-wheel side actuator (what actually affects the tire slip angles)
    rwa_cmd = clamp(rwa_cmd, -params.max_rwa, params.max_rwa)
    delta_rwa_dot = (rwa_cmd - state.delta_rwa) / max(params.tau_rwa, 1e-6)
    delta_rwa_dot = clamp(delta_rwa_dot, -params.max_rwa_rate, params.max_rwa_rate)
    delta_rwa_next = clamp(state.delta_rwa + dt * delta_rwa_dot, -params.max_rwa, params.max_rwa)

    # Steering-wheel side actuator / feel side dynamics
    sfa_cmd = clamp(sfa_cmd, -params.max_sfa, params.max_sfa)
    delta_sfa_dot = (sfa_cmd - state.delta_sfa) / max(params.tau_sfa, 1e-6)
    delta_sfa_dot = clamp(delta_sfa_dot, -params.max_sfa_rate, params.max_sfa_rate)
    delta_sfa_next = clamp(state.delta_sfa + dt * delta_sfa_dot, -params.max_sfa, params.max_sfa)

    # 2) Tire lateral forces (linear tire model) ---------------------------
    # Sign convention:
    #   alpha_f = delta_rwa - (vy + lf*r)/vx
    #   alpha_r = -(vy - lr*r)/vx
    alpha_f = delta_rwa_next - (state.vy + params.lf * state.r) / vx
    alpha_r = -(state.vy - params.lr * state.r) / vx

    fy_f = 2.0 * params.cf * alpha_f
    fy_r = 2.0 * params.cr * alpha_r

    # 3) Lateral / yaw dynamics -------------------------------------------
    vy_dot = (fy_f + fy_r) / params.m - vx * state.r
    r_dot = (params.lf * fy_f - params.lr * fy_r) / params.iz

    vy_next = state.vy + dt * vy_dot
    r_next = state.r + dt * r_dot

    # 4) Global kinematics -------------------------------------------------
    x_dot = vx * math.cos(state.psi) - state.vy * math.sin(state.psi)
    y_dot = vx * math.sin(state.psi) + state.vy * math.cos(state.psi)
    psi_next = state.psi + dt * state.r
    x_next = state.x + dt * x_dot
    y_next = state.y + dt * y_dot

    return VehicleState(
        x=x_next,
        y=y_next,
        psi=psi_next,
        vy=vy_next,
        r=r_next,
        delta_rwa=delta_rwa_next,
        delta_sfa=delta_sfa_next,
        lam=state.lam,
        t=state.t + dt,
    )
